# Generated by Django 5.2.8 on 2025-11-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('telefone', models.CharField(max_length=50, verbose_name='Telefone')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('total_emprestimos', models.IntegerField(default=0, verbose_name='Total de Empréstimos')),
                ('emprestimos_ativos', models.IntegerField(default=0, verbose_name='Empréstimos Ativos')),
                ('emprestimos_atrasados', models.IntegerField(default=0, verbose_name='Empréstimos Atrasados')),
                ('total_atraso_historico', models.IntegerField(default=0, verbose_name='Total de Atrasos no Histórico')),
                ('data_ultimo_emprestimo', models.DateTimeField(blank=True, null=True, verbose_name='Data do Último Empréstimo')),
                ('limite_emprestimos', models.IntegerField(default=5, verbose_name='Limite de Empréstimos')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['id'],
            },
        ),
    ]
