# Generated by Django 5.2.8 on 2025-11-19 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autor', '0001_initial'),
        ('editora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('ano_publicacao', models.PositiveIntegerField(verbose_name='Ano de Publicação')),
                ('edicao', models.CharField(max_length=50, verbose_name='Edição')),
                ('sinopse', models.TextField(blank=True, null=True, verbose_name='Sinopse')),
                ('capa_url', models.URLField(blank=True, null=True, verbose_name='URL da Capa')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autor.autor', verbose_name='Autor')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editora.editora', verbose_name='Editora')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['id'],
            },
        ),
    ]
