# Generated by Django 5.2.8 on 2025-11-19 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0001_initial'),
        ('exemplar', '0002_exemplar_capa_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='exemplar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exemplar.exemplar'),
        ),
    ]
