# Generated by Django 5.2.8 on 2025-11-19 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_de_barras', models.CharField(max_length=100, unique=True)),
                ('data_aquisicao', models.DateField(verbose_name='Data de Aquisição')),
                ('estado_de_convervacao', models.CharField(max_length=100, verbose_name='Estado de Conservação')),
                ('preco_de_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Compra')),
                ('localizacao', models.CharField(max_length=100, verbose_name='Localização')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.biblioteca', verbose_name='Biblioteca')),
            ],
            options={
                'verbose_name': 'Exemplar',
                'verbose_name_plural': 'Exemplares',
                'ordering': ['id'],
            },
        ),
    ]
