# Generated by Django 5.2.8 on 2025-11-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemplar',
            name='capa_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL da Capa'),
        ),
    ]
