# Generated by Django 5.2.8 on 2025-11-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplar', '0002_exemplar_capa_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exemplar',
            name='capa_url',
        ),
        migrations.AddField(
            model_name='exemplar',
            name='foto_capa',
            field=models.ImageField(blank=True, null=True, upload_to='exemplar_covers/', verbose_name='Foto da Capa'),
        ),
    ]
