# Generated by Django 5.2.8 on 2025-11-19 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplar', '0003_remove_exemplar_capa_url_exemplar_foto_capa'),
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemplar',
            name='livro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='livro.livro', verbose_name='Livro'),
        ),
    ]
